language: go
go:
  - 1.12

addons:
  artifacts:
    s3_region: "us-east-1"
    paths:
      - $HOME/logs
    target-paths:
      - artifacts/

before_install:
  - docker pull golang:latest

install:
  - >
    git clone --single-branch --branch v1.4.3
    https://github.com/hyperledger/fabric.git
    ${GOPATH}/src/github.com/hyperledger/fabric &&
    
    cd ${GOPATH}/src/github.com/hyperledger/fabric &&
    git apply ${GOPATH}/src/${TRAVIS_GO_IMPORT_PATH}/fabric.patch &&
    curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh &&
    dep ensure &&
    make protos &&
    make peer-docker &&
    make orderer-docker &&
    cd $HOME && curl -sSL http://bit.ly/2ysbOFE | bash -s -- '-d' &&

    cd ${GOPATH}/src/${TRAVIS_GO_IMPORT_PATH}/test &&
    git clone --single-branch --branch v1.0.0-beta1 https://github.com/hyperledger/fabric-sdk-go &&
    cd fabric-sdk-go && git apply ${GOPATH}/src/${TRAVIS_GO_IMPORT_PATH}/sdk.patch


before_script:
  - cd $HOME/fabric-samples/first-network && echo y | ./byfn.sh up

script:
  - >
    docker run -t
    -v ${GOPATH}:/go
    -v $HOME/fabric-samples/first-network/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
    -w /go/src/${TRAVIS_GO_IMPORT_PATH}/test
    --network=net_byfn
    golang:latest
    go test -v -failfast ./main_test.go

after_success:
  - >
    docker tag hyperledger/fabric-peer ilyapt/patched-fabric-peer &&
    docker tag hyperledger/fabric-orderer ilyapt/patched-fabric-orderer &&
    echo "$DOCKER_PASSWD" | docker login -u ilyapt --password-stdin &&
    docker push ilyapt/patched-fabric-peer && docker push ilyapt/patched-fabric-orderer &&

    mkdir -p $HOME/.ssh && echo "$DEPLOY_SSH_KEY" | base64 -d -w 0 > $HOME/.ssh/id_rsa &&
    chmod 400 $HOME/.ssh/id_rsa &&
    ssh-keyscan -t rsa github.com > $HOME/.ssh/known_hosts &&
    cd $HOME && git clone -n git@github.com:ilyapt/fabric-sdk-go-patched.git

    cd ${GOPATH}/src/${TRAVIS_GO_IMPORT_PATH}/test/fabric-sdk-go &&
    rm -rf .git && mv $HOME/fabric-sdk-go-patched/.git . &&
    git reset README.md && git checkout -- README.md &&
    git config user.name "Travis-CI" && git add . &&
    git commit -m "based on https://github.com/ilyapt/fabric-certstore/commit/${TRAVIS_COMMIT}" > /dev/null &&
    git push origin master

after_script:
  - >
    mkdir -p $HOME/logs &&
    for x in `docker ps -a --format '{{.Names}}'`; do docker logs $x > $HOME/logs/$x.log 2>&1; done &&
    tar cfz $HOME/logs/logs.tgz $HOME/logs/*.log &&
    rm -rf $HOME/logs/*.log
